import { Dumbbell, FileWarning as Running, ArrowUp, Armchair, Footprints, Activity, Heart, Leaf, Waves, Mountain } from 'lucide-react-native';
import categoryVideos from '@/constants/videos-category';

export const imagenes = {
  Abdominales: require('../assets/images/categorias/abdominales.png'),
  Abductor: require('../assets/images/categorias/abductor.png'),
  Cuádriceps: require('../assets/images/categorias/cuadriceps.png'),
  Deltoides: require('../assets/images/categorias/deltoides.png'),
  Glúteos: require('../assets/images/categorias/gluteos.png'),
  Isquios: require('../assets/images/categorias/isquios.png'),
  Pectoral: require('../assets/images/categorias/pectoral.png'),
  Trapecio: require('../assets/images/categorias/trapecio.png'),
  Tríceps: require('../assets/images/categorias/triceps.png'),
  TécnicaDeCarrera: require('../assets/images/categorias/tecnica-de-carrera.png'),
  Pliométricos: require('../assets/images/categorias/pliometricos.png'),
};

export const categories = [
  {
    id: 'abs',
    title: 'Abdominales',
    description: 'Ejercicios para el core',
    icon: Activity,
    image: imagenes.Abdominales,
    color: '#EF4444',
    videoCount: categoryVideos['abs']?.length || 0,
  },
  {
    id: 'abductor',
    title: 'Abductor',
    description: 'Ejercicios para aductores',
    icon: Footprints,
    image: imagenes.Abductor,
    color: '#3B82F6',
    videoCount: categoryVideos['abductor']?.length || 0,
  },
  {
    id: 'cuádriceps',
    title: 'Cuádriceps',
    description: 'Ejercicios para cuádriceps',
    icon: Footprints,
    image: imagenes.Cuádriceps,
    color: '#F59E0B',
    videoCount: categoryVideos['cuádriceps']?.length || 0,
  },
  {
    id: 'deltoides',
    title: 'Deltoides',
    description: 'Ejercicios para hombros',
    icon: Waves,
    image: imagenes.Deltoides,
    color: '#10B981',
    videoCount: categoryVideos['deltoides']?.length || 0,
  },
  {
    id: 'glúteos',
    title: 'Glúteos',
    description: 'Ejercicios para glúteos',
    icon: Heart,
    image: imagenes.Glúteos,
    color: '#6366F1',
    videoCount: categoryVideos['glúteos']?.length || 0,
  },
  {
    id: 'isquios',
    title: 'Isquiotibiales',
    description: 'Ejercicios para isquios',
    icon: Leaf,
    image: imagenes.Isquios,
    color: '#EC4899',
    videoCount: categoryVideos['isquios']?.length || 0,
  },
  {
    id: 'pectoral',
    title: 'Pectoral',
    description: 'Ejercicios para pecho',
    icon: Dumbbell,
    image: imagenes.Pectoral,
    color: '#8B5CF6',
    videoCount: categoryVideos['pectoral']?.length || 0,
  },
  {
    id: 'trapecio',
    title: 'Trapecio',
    description: 'Ejercicios para trapecios',
    icon: Mountain,
    image: imagenes.Trapecio,
    color: '#F472B6',
    videoCount: categoryVideos['trapecio']?.length || 0,
  },
  {
    id: 'tríceps',
    title: 'Tríceps',
    description: 'Ejercicios para tríceps',
    icon: Armchair,
    image: imagenes.Tríceps,
    color: '#2DD4BF',
    videoCount: categoryVideos['tríceps']?.length || 0,
  },
  {
    id: 'técnica_de_carrera',
    title: 'Técnica de Carrera',
    description: 'Ejercicios de técnica de carrera',
    icon: Running,
    image: imagenes.TécnicaDeCarrera,
    color: '#FB923C',
    videoCount: categoryVideos['técnica_de_carrera']?.length || 0,
  },
  {
    id: 'pliométricos',
    title: 'Pliométricos',
    description: 'Ejercicios pliométricos',
    icon: ArrowUp,
    image: imagenes.Pliométricos,
    color: '#0EA5E9',
    videoCount: categoryVideos['pliométricos']?.length || 0,
  },
];
